---
abstract: 'Implementation for Unixish, a data transformation framework'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Unixish
requires:
  Log::Any: 0
  Number::Format: 0
  Rinci: v1.1.0
  SHARYANTO::Number::Util: 0.38
  SHARYANTO::Package::Util: 0
  SHARYANTO::String::Util: 0.24
  Syntax::Feature::EachOnArray: 0
  Text::ANSI::Util: 0.06
  Text::WideChar::Util: 0.03
  Text::sprintfn: 0
  Tie::Simple: 0
  Unixish: v1.0.1
  perl: 5.010001
resources:
  homepage: https://metacpan.org/release/Data-Unixish
  repository: http://github.com/sharyanto/perl-Data-Unixish
version: 1.39
